name: Basic Go

permissions: {}

on:
  workflow_call:
    inputs:
      go-versions:
        type: string
        # Arrays are currently not accepted:
        # https://github.com/orgs/community/discussions/11692
        default: "['stable' , 'oldstable']"
      staticcheck-version:
        type: string
        default: "latest"
      static-analysis-excludes-regex:
        type: string
      # TODO(wenvous): gofmt is harder to work with since it always recursively
      # formats files instead of restricting itself to just listed packages.
      # See if there is a way to have the same behaviour without relying on the
      # tool.
      tests-excludes-regex:
        type: string
        description: "grep -E regex for excluding certain packages from testing"
      race-tests-excludes-regex:
        type: string
        description: "grep -E regex for excluding certain packages from race testing, this DOES NOT include packages excluded from regular testing"
      coverage-excludes-regex:
        type: string
        description: "grep -E regex for excluding certain packages from coverage reporting"
      skip-gofmt:
        type: boolean
      skip-govet:
        type: boolean
      skip-staticcheck:
        type: boolean
      skip-race-tests:
        type: boolean
      install-additional-apt-packages:
        type: string
        description: "apt-get install additional apt packages"

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ${{ fromJson(inputs.go-versions) }}
    permissions:
      contents: read

    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Get dependencies
        run: |
          go mod download

      - name: Install additional dependencies
        run: |
          if [ -n "${{ inputs.install-additional-apt-packages }}" ]; then
            echo "Installing additional packages"
            sudo apt-get install ${{ inputs.install-additional-apt-packages }}
          fi

      - name: Build packages
        run: go build -v ./...

      - name: Run Tests
        run: |
          if [ -z "${{ inputs.tests-excludes-regex }}" ]; then
            echo "Running for all packages"
            go test -v ./...
          else
            echo "Running for non-excluded packages"
            go test -v $(go list ./... | grep -E -v "${{ inputs.tests-excludes-regex }}")
          fi

      - name: Run race tests
        if: ${{ !inputs.skip-race-tests }}
        run: |
          if [ -z "${{ inputs.race-tests-excludes-regex }}" ]; then
            echo "Running for all packages"
            go test -race -v ./...
          else
            echo "Running for non-excluded packages"
            go test -race -v $(go list ./... | grep -E -v "${{ inputs.race-tests-excludes-regex }}")
          fi

  static_analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # For goveralls to submit coverage
      statuses: write

    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version: "stable"
        id: go

      - name: Get dependencies
        run: |
          go mod download

      - name: Install additional dependencies
        run: |
          if [ -n "${{ inputs.install-additional-apt-packages }}" ]; then
            echo "Installing additional packages"
            sudo apt-get install ${{ inputs.install-additional-apt-packages }}
          fi

      - name: Go Mod should be tidy
        run: |
          go mod tidy
          diff -u <(echo -n) <(git diff)

      - name: Go vet
        if: ${{ !cancelled() && !inputs.skip-govet }}
        run: |
          if [ -z "${{ inputs.static-analysis-excludes-regex }}" ]; then
            echo "Running for all packages"
            go vet ./...
          else
            echo "Running for non-excluded packages"
            go vet $(go list ./... | grep -E -v "${{ inputs.static-analysis-excludes-regex }}")
          fi

      - name: revive
        if: ${{ !cancelled() }}
        run: |
          go install github.com/mgechev/revive@latest
          if [ -z "${{ inputs.static-analysis-excludes-regex }}" ]; then
            echo "Running for all packages"
            revive ./...
          else
            echo "Running for non-excluded packages"
            revive $(go list ./... | grep -E -v ${{ inputs.static-analysis-excludes-regex }})
          fi

      - name: Gofmt
        if: ${{ !cancelled() && !inputs.skip-gofmt }}
        run: |
          diff -u <(echo -n) <(gofmt -d -s .)

      - name: Run coverage
        # Always run unless manually cancelled.
        if: ${{ !cancelled() }}
        run: |
          if [ -z "${{ inputs.coverage-excludes-regex }}" ]; then
            echo "Running for all packages"
            go test -v -coverprofile=profile.cov ./...
          else
            echo "Running for non-excluded packages"
            go test -v -coverprofile=profile.cov $(go list ./... | grep -E -v "${{ inputs.coverage-excludes-regex }}")
          fi

      - name: Install goveralls
        if: ${{ !cancelled() }}
        run: go install github.com/mattn/goveralls@latest

      - name: Submit coverage
        if: ${{ !cancelled() }}
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=profile.cov -service=github

  staticcheck:
    name: staticcheck
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version: "stable"
        id: go

      - name: Install staticcheck
        if: ${{ !cancelled() }}
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@${{ inputs.staticcheck-version }}

      - name: Cache for staticcheck
        if: ${{ !cancelled() && !inputs.skip-staticcheck }}
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        with:
          path: |
            ${{ runner.temp }}/staticcheck
          key: ${{ github.job }}-${{ steps.go.outputs.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ github.job }}-${{ steps.go.outputs.go-version }}-${{ hashFiles('**/go.sum') }}

      - name: Install additional dependencies
        run: |
          if [ -n "${{ inputs.install-additional-apt-packages }}" ]; then
            echo "Installing additional packages"
            sudo apt-get install ${{ inputs.install-additional-apt-packages }}
          fi

      - name: Staticcheck
        if: ${{ !cancelled() && !inputs.skip-staticcheck }}
        run: |
          export STATICCHECK_CACHE="${{ runner.temp }}/staticcheck"
          if [ -z "${{ inputs.static-analysis-excludes-regex }}" ]; then
            echo "Running for all packages"
            GOGC=30 staticcheck ./...
          else
            echo "Running for non-excluded packages"
            GOGC=30 staticcheck $(go list ./... | grep -E -v ${{ inputs.static-analysis-excludes-regex }})
          fi
